/**
 * Bilingual message catalogue.
 *
 * Format: key -> [English, Azərbaycanca]
 *
 * Rules:
 *  - English is deliberately simple and short (this bot is used by non-native speakers).
 *  - Placeholders must be identical in both languages, otherwise a message will break
 *    when the server language is not the default one.
 *  - Real Discord names (channel/role/category names such as "sayı-sayma", "Rəhbər",
 *    "Dəstək") are NOT here. They are identifiers, not text, so they are never
 *    translated. The few entries under "FUNCTIONAL NAMES" are kept on purpose so
 *    that setup keeps creating exactly the same channel names in both languages.
 */

module.exports = {
    // ---------------------------------------------------------------- common
    no_permission: ['You do not have the required permissions for this command.', 'Bu əmr üçün lazım olan icazələriniz yoxdur.'],
    cannot_manage_member: ['You cannot manage this member: check the role hierarchy.', 'Bu istifadəçini idarə edə bilməzsiniz: rollar sırasını yoxlayın.'],
    user_not_found: ['User not found.', 'İstifadəçi tapılmadı.'],
    member_not_found: ['Member not found.', 'Üzv tapılmadı.'],
    common_unknown: ['Unknown', 'Naməlum'],
    ping_pending: ['pending', 'gözlənilir'],
    ping_line_bot: ['Bot latency', 'Bot gecikməsi'],
    ping_line_api: ['Discord API', 'Discord API'],
    ping_line_gateway: ['Gateway', 'Gateway'],
    foxcraft_this_server: ['This server', 'Bu server'],
    foxcraft_tagline: ['Minecraft server\nAzerbaijan Minecraft community', 'Minecraft server\nAzərbaycan Minecraft icması'],
    status_live_title: ['FoxCraft live status', 'FoxCraft canlı statusu'],
    status_ip_coming: ['The server IP will be available soon.', 'Server IP-si Yaxında olacaq.'],
    status_unreachable: ['The server could not be pinged.', 'Serverə ping göndərmək mümkün olmadı.'],
    server_status_unavailable: ['The status is not available right now.', 'Status hazırda müəyyən edilə bilmir.'],
    serverinfo_no_description: ['No description', 'Təsvir yoxdur'],
    unknown_user: ['Unknown User', 'Naməlum İstifadəçi'],
    server_only: ['This command can only be used on a server.', 'Bu əmr yalnız serverdə istifadə oluna bilər.'],
    command_failed: ['The command could not be completed.', 'Əmr yerinə yetirilmədi.'],
    something_went_wrong: ['Something went wrong while running this action.', 'Bu əməliyyat icra olunarkən xəta baş verdi.'],
    target_member: ['Target member', 'Hədəf üzv'],
    target_user: ['Target user', 'Hədəf istifadəçi'],
    reason: ['Reason', 'Səbəb'],
    voice_channel_not_found: ['That voice channel was not found.', 'Səs kanalı tapılmadı.'],
    role_not_found: ['The selected role was not found.', 'Seçilmiş rol tapılmadı.'],
    channel_not_found: ['That channel was not found.', 'Kanal tapılmadı.'],

    // --------------------------------------------------------- permissions
    perm_manage_channels: ['Manage Channels permission is required to use this command.', 'Bu əmri üçün Manage Channels icazəsi lazımdır.'],
    perm_manage_roles: ['Manage Roles permission is required to use this command.', 'Bu əmri üçün Manage Roles icazəsi lazımdır.'],
    perm_manage_guild: ['Manage Guild permission is required to use this command.', 'Bu əmri üçün Manage Guild icazəsi lazımdır.'],
    perm_manage_messages: ['Manage Messages permission is required to use this command.', 'Bu əmri üçün Manage Messages icazəsi lazımdır.'],
    perm_manage_nicknames: ['Manage Nicknames permission is required to use this command.', 'Bu əmri üçün Manage Nicknames icazəsi lazımdır.'],
    perm_ban_members: ['Ban Members permission is required to use this command.', 'Bu əmri üçün Ban Members icazəsi lazımdır.'],
    perm_admin_only: ['Only administrators can use this command.', 'Bu əmri yalnız Administratorlar istifadə edə bilər.'],
    perm_owner_only: ['Only the bot owner can use this command.', 'Bu əmrdən yalnız bot sahibi istifadə edə bilər.'],
    perm_owner_or_admin: ['Only the server owner, an administrator, or the bot owner can use this command.', 'Bu əmrdən yalnız server sahibi, administrator və ya bot sahibi istifadə edə bilər.'],
    perm_panel_owner: ['Only the bot owner can use this panel.', 'Bu paneldən yalnız bot sahibi istifadə edə bilər.'],

    // -------------------------------------------------------------- music
    nothing_playing: ['Nothing is playing right now.', 'Hazırda heç nə çalmır.'],
    joined_voice: ['Joined **{channel}**. Use `!play <track>` to start playback.', '**{channel}** kanalına qoşuldu. Başlatmaq üçün `!play <trek>` istifadə edin.'],
    volume_set: ['Volume set to **{volume}%**.', 'Səs səviyyəsi **{volume}%** təyin edildi.'],
    loop_set: ['Loop mode set to **{mode}**.', 'Təkrar rejimi **{mode}** təyin edildi.'],
    replaying: ['Replaying the current track.', 'Cari trekdən yenidən başlayır.'],
    skipped_now: ['Skipped. Now playing: **{title}**', 'Keçildi. İndi çalır: **{title}**'],
    join_first: ['Join a voice channel first, or use `!join <channel>`, then run the command again.', 'Əvvəlcə səs kanalına qoşulun və ya `!join <kanal>` istifadə edin, sonra əmri təkrar edin.'],
    play_join_first: ['Join a voice channel first, then run the command again.', 'Əvvəlcə səs kanalına qoşulun, sonra əmri təkrar edin.'],
    cannot_join: ['I cannot join that voice channel.', 'O səs kanalına qoşula bilmirəm.'],
    need_connect_speak: ['I need the **Connect** and **Speak** permissions in that voice channel.', 'O səs kanalında **Connect** və **Speak** icazələri lazımdır.'],
    move_no_perm: ['I cannot move members into that channel — check my permissions there.', 'O kanala istifadəçi köçürə bilmirəm — icazələrimi yoxlayın.'],
    member_not_moved: ['The member could not be moved.', 'Üzv köçürülə bilmədi.'],
    member_moved: ['{user} was moved to **{channel}**.', '{user} **{channel}** kanalına köçürüldü.'],
    usage_play: ['Usage: `!play <title or YouTube link>`', 'İstifadə: `!play <ad və ya YouTube link>`'],
    usage_move: ['Usage: `!move @member <voice-channel>`', 'İstifadə: `!move @üzv <səs-kanalı>`'],
    usage_join: ['Usage: `!join <channel>`', 'İstifadə: `!join <kanal>`'],
    opt_track: ['Title, search term or YouTube link', 'Ad, açar söz və ya YouTube link'],
    opt_voice_channel: ['Voice channel (defaults to yours)', 'Səs kanalı (yoksa sizin kanalınız)'],
    opt_volume: ['Volume between 0 and {max}', 'Səs səviyyəsi 0 və {max} arasında'],
    opt_loop: ['off, track or queue', 'off, track və ya queue'],
    track_not_found: ['No track was found for your search.', 'Axtarışınız üçün trek tapılmadı.'],
    queue_empty: ['The queue is empty.', 'Növbə boşdur.'],

    // --------------------------------------------------------- moderation
    usage_action: ['Usage: `!{name} @member [reason]`', 'İstifadə: `!{name} @üzv [səbəb]`'],
    action_failed: ['The {name} action could not be completed.', '{name} əməliyyatı yerinə yetirilmədi.'],
    usage_warn: ['Usage: `!warn @member [reason]`', 'İstifadə: `!warn @üzv [səbəb]`'],
    warn_issued: ['{user} was warned ({total} total).{extra}', '{user} xəbərdar edildi ({total} cəmi).{extra}'],
    warn_automute_done: [' They have now been muted for 1 hour ({count} warnings reached).', ' Artıq 1 saatlığa susduruldu ({count} xəbərdarlıq sayına çatıldı).'],
    warn_automute_failed: [' They could not be muted automatically.', ' Avtomatik susdurma edilə bilmədi.'],
    warn_failed: ['The warning could not be issued.', 'Xəbərdarlıq verilmədi.'],
    opt_warn_reason: ['Reason', 'Səbəb'],
    usage_warnings: ['Usage: `!warnings @member`', 'İstifadə: `!warnings @üzv`'],
    warnings_title: ['Warnings', 'Xəbərdarlıqlar'],
    warnings_none: ['This member has no warnings.', 'Bu üzvün xəbərdarlığı yoxdur.'],
    warnings_failed: ['The warnings could not be loaded.', 'Xəbərdarlıqlar yüklənmədi.'],
    usage_removewarn: ['Usage: `!removewarn @member [warning-id]`', 'İstifadə: `!removewarn @üzv [xəbərdarlıq-id]`'],
    warn_removed: ['Removed warning #{id} from {user}.', '{user} üzvündən #{id} xəbərdarlığı silindi.'],
    warns_removed_all: ['Removed all {total} warnings from {user}.', '{user} üzvündən bütün {total} xəbərdarlıq silindi.'],
    warn_not_found: ['No warning with that id was found.', 'Bu id ilə xəbərdarlıq tapılmadı.'],
    warn_remove_failed: ['The warning could not be removed.', 'Xəbərdarlıq silinmədi.'],
    opt_warn_id: ['Warning id to remove', 'Silinəcək xəbərdarlıq id'],

    usage_timeout: ['Usage: `!timeout @member <duration> [reason]` (max 28 days)', 'İstifadə: `!timeout @üzv <müddət> [səbəb]` (max 28 gün)'],
    timeout_applied: ['{user} was timed out for {duration}.', '{user} {duration} müddətinə vaxtında çıxarıldı.'],
    timeout_removed: ['The timeout for {user} was removed.', '{user} üzvünün timeout-u ləğv edildi.'],
    timeout_failed: ['The timeout could not be applied.', 'Timeout tətbiq olunmadı.'],
    timeout_lift_failed: ['The timeout could not be lifted.', 'Timeout qaldırılmadı.'],
    usage_untimeout: ['Usage: `!untimeout @member [reason]`', 'İstifadə: `!untimeout @üzv [səbəb]`'],
    timeout_lifted: ['The timeout on {user} was lifted.', '{user} üzvünün timeout-u qaldırıldı.'],
    opt_duration: ['Duration, e.g. 10m, 2h, 7d', 'Müddət, məs: 10m, 2h, 7d'],
    opt_duration_mute: ['Duration, e.g. 1h30m (10m max 28d)', 'Müddət, məs: 1h30m (10m, max 28d)'],

    usage_mute: ['Usage: `!mute @member <duration> [reason]` (duration: 1h30m)', 'İstifadə: `!mute @üzv <müddət> [səbəb]` (müddət: 1h30m)'],
    user_muted: ['{user} was muted for {duration}.', '{user} {duration} müddətinə susduruldu.'],
    user_not_muted: ['{user} is not muted.', '{user} susdurulmayıb.'],
    mute_failed: ['The mute action could not be completed.', 'Susturma əməliyyatı yerinə yetirilmədi.'],
    usage_unmute: ['Usage: `!unmute @member [reason]`', 'İstifadə: `!unmute @üzv [səbəb]`'],
    user_unmuted: ['{user} was unmuted.', '{user} üzvünün susturması ləğv edildi.'],
    unmute_failed: ['The unmute action could not be completed.', 'Susturmanın ləğvi əməliyyatı yerinə yetirilmədi.'],

    usage_unban: ['Usage: `!unban <user_id> [reason]`', 'İstifadə: `!unban <istifadəçi_id> [səbəb]`'],
    user_not_banned: ['This user is not banned.', 'Bu istifadəçi qadağan deyil.'],
    ban_removed: ['The ban for {user} was removed.', '{user} üçün qadağa qaldırıldı.'],
    unban_failed: ['The unban action could not be completed.', 'Qadağanın ləğvi əməliyyatı yerinə yetirilmədi.'],

    usage_softban: ['Usage: `!softban @member [reason] [--keep]`', 'İstifadə: `!softban @üzv [səbəb] [--keep]`'],
    softban_done: ['{user} was softbanned.', '{user} softban edildi.'],
    softban_failed: ['The softban could not be completed.', 'Softban əməliyyatı yerinə yetirilmədi.'],

    usage_kick: ['Usage: `!kick @member [reason]`', 'İstifadə: `!kick @üzv [səbəb]`'],
    user_kicked: ['{user} was kicked.', '{user} serverdən atıldı.'],

    usage_clear: ['Usage: `!clear <1-100>`', 'İstifadə: `!clear <1-100>`'],
    messages_deleted: ['Deleted {count} messages.', '{count} mesaj silindi.'],
    clear_failed: ['The messages could not be deleted.', 'Mesajlar silinmədi.'],
    opt_clear_count: ['Number of messages between 1 and 100', '1 ilə 100 arasında mesaj sayı'],

    usage_nickname: ['Usage: `!nickname @member [new nickname]`', 'İstifadə: `!nickname @üzv [yeni ləqəb]`'],
    nickname_changed: ['Nickname for {user} was changed to **{nickname}**.', '{user} üzvünün ləqəbi **{nickname}** oldu.'],
    nickname_reset: ['Nickname for {user} was reset.', '{user} üzvünün ləqəbi sıfırlandı.'],
    nickname_failed: ['The nickname could not be changed.', 'Ləqəb dəyişdirilmədi.'],
    opt_new_nickname: ['New nickname (empty to reset it)', 'Yeni ləqəb (sıfırlamaq üçün boş buraxın)'],

    usage_lock: ['Usage: `!lock [reason]`', 'İstifadə: `!lock [səbəb]`'],
    channel_locked: ['{channel} was locked.', '{channel} kanalı kilidləndi.'],
    channel_already_locked: ['This channel is already locked.', 'Bu kanal artıq kilidlidir.'],
    lock_failed: ['The channel could not be locked.', 'Kanal kilidlənmədi.'],
    usage_unlock: ['Usage: `!unlock [reason]`', 'İstifadə: `!unlock [səbəb]`'],
    channel_unlocked: ['{channel} was unlocked.', '{channel} kanalı açıldı.'],
    channel_already_unlocked: ['This channel is already unlocked.', 'Bu kanal artıq açıqdır.'],
    unlock_failed: ['The channel could not be unlocked.', 'Kanal açıla bilmədi.'],

    usage_slowmode: ['Usage: `!slowmode <0-21600>`', 'İstifadə: `!slowmode <0-21600>`'],
    slowmode_set: ['Slowmode for {channel} set to **{seconds} seconds**.', '{channel} kanalında slowmode **{seconds} saniyə** təyin edildi.'],
    slowmode_failed: ['The slowmode could not be applied.', 'Slowmode tətbiq olunmadı.'],
    opt_slowmode: ['Seconds between 0 and 21600 (0 disables slowmode)', '0 və 21600 arasında saniyə (0 slowmode-u söndürür)'],

    usage_addrole: ['Usage: `!addrole @member @role`', 'İstifadə: `!addrole @üzv @rol`'],
    role_given: ['{role} was given to {user}.', '{user} üzvünə {role} verildi.'],
    role_give_failed: ['The role could not be given.', 'Rol verilmədi.'],
    role_hierarchy_give: ['You cannot assign that role: your highest role must be above it.', 'O rolı verə bilməzsiniz: ən yüksək rolunuz ondan yuxarıda olmalıdır.'],
    role_integrated_give: ['That role is managed by an integration and cannot be assigned.', 'Bu rol inteqrasiya tərəfindən idarə olunur və verilə bilməz.'],
    opt_role_to_give: ['Role to give', 'Veriləcək rol'],
    usage_removerole: ['Usage: `!removerole @member @role`', 'İstifadə: `!removerole @üzv @rol`'],
    role_removed: ['{role} was removed from {user}.', '{user} üzvündən {role} silindi.'],
    role_remove_failed: ['The role could not be removed.', 'Rol silinmədi.'],
    role_hierarchy_remove: ['You cannot remove that role: your highest role must be above it.', 'O rolü silə bilməzsiniz: ən yüksək rolunuz ondan yuxarıda olmalıdır.'],
    role_integrated_remove: ['That role is managed by an integration and cannot be removed.', 'Bu rol inteqrasiya tərəfindən idarə olunur və silinə bilməz.'],
    opt_role_to_remove: ['Role to remove', 'Silinəcək rol'],

    // --------------------------------------------------- moderation log UI
    log_title_author: ['Author', 'Müəllif'],
    log_title_channel: ['Channel', 'Kanal'],
    log_title_message: ['Message Deleted', 'Mesaj Silindi'],
    log_title_member_joined: ['Member Joined', 'Üzv Qoşuldu'],
    log_title_member_left: ['Member Left', 'Üzv Ayrıldı'],
    log_title_roles_added: ['Roles Added to Member', 'Üzvə Rol Əlavə Edildi'],
    log_title_roles_removed: ['Roles Removed from Member', 'Üzvün Rolu Silindi'],
    log_title_nickname: ['Nickname Changed', 'Ləqəb Dəyişdi'],
    log_title_member_banned: ['Member Banned', 'Üzv Qadağan Edildi'],
    log_title_member_unbanned: ['Member Unbanned', 'Qadağa Ləğv Edildi'],
    log_title_member_kicked: ['Member Kicked', 'Üzv Atıldı'],
    log_title_bulk_deleted: ['Bulk Messages Deleted', 'Toplu Mesaj Silindi'],
    log_title_voice_join: ['Joined Voice Channel', 'Səs Kanalına Qoşuldu'],
    log_title_voice_leave: ['Left Voice Channel', 'Səs Kanalından Ayrıldı'],
    log_title_voice_move: ['Moved Voice Channel', 'Səs Kanalı Dəyişdi'],
    log_title_channel_created: ['Channel Created', 'Kanal Yaradıldı'],
    log_title_channel_updated: ['Channel Updated', 'Kanal Yeniləndi'],
    log_title_channel_deleted: ['Channel Deleted', 'Kanal Silindi'],
    log_title_role_created: ['Role Created', 'Rol Yaradıldı'],
    log_title_role_updated: ['Role Updated', 'Rol Yeniləndi'],
    log_title_role_deleted: ['Role Deleted', 'Rol Silindi'],
    log_title_server_updated: ['Server Updated', 'Server Yeniləndi'],
    log_title_message_edited: ['Message Edited', 'Mesaj Redaktə Edildi'],
    log_field_user: ['User', 'İstifadəçi'],
    log_field_member: ['Member', 'Üzv'],
    log_field_server: ['Server', 'Server'],
    log_field_content: ['Content', 'Məzmun'],
    log_field_new_content: ['New content', 'Yeni məzmun'],
    log_field_old_content: ['Old content', 'Köhnə məzmun'],
    log_field_reason: ['Reason', 'Səbəb'],
    log_field_type: ['Type', 'Növ'],
    log_field_actor: ['Performed by', 'İcra edən'],
    log_field_deleted_by: ['Deleted by', 'Silən'],
    log_field_banned_by: ['Banned by', 'Qadağan edən'],
    log_field_banned_user: ['Banned user', 'Qadağan edilen istifadəçi'],
    log_field_unbanned_by: ['Unbanned by', 'Qadağanı ləğv edən'],
    log_field_kicked_by: ['Kicked by', 'Atan'],
    log_field_account_created: ['Account created', 'Hesab yaradılma'],
    log_field_member_count: ['Member count', 'Üzv sayı'],
    log_field_joined_on: ['Joined on', 'Qoşulma tarixi'],
    log_field_changes: ['Changes', 'Dəyişikliklər'],
    log_field_attachments: ['Attachments ({count})', 'Qoşulmalar ({count})'],
    log_field_sample: ['Sample of recent messages', 'Son mesajların nümunəsi'],
    log_field_new_channel: ['New channel', 'Yeni kanal'],
    log_field_old_channel: ['Old channel', 'Köhnə kanal'],
    log_field_channel_name: ['Channel name', 'Kanal adı'],
    log_field_role_name: ['Role name', 'Rol adı'],
    log_field_new_nickname: ['New nickname', 'Yeni ləqəb'],
    log_field_old_nickname: ['Old nickname', 'Köhnə ləqəb'],
    log_field_roles_added: ['Roles added', 'Əlavə edilən rollar'],
    log_field_roles_removed: ['Roles removed', 'Silinən rollar'],
    log_field_displayed_separately: ['Displayed separately (hoist)', 'Ayrıca göstərilir (hoist)'],
    log_field_can_be_mentioned: ['Can be mentioned', 'Qeyd edilə bilər'],
    log_field_color: ['Color', 'Rəng'],
    log_field_id: ['ID', 'ID'],
    log_field_link: ['Link', 'Link'],

    // --------------------------------------------------------- user / server
    userinfo_title: ['User Info', 'İstifadəçi Məlumatı'],
    userinfo_user: ['User', 'İstifadəçi'],
    userinfo_id: ['User ID', 'İstifadəçi ID'],
    userinfo_nickname: ['Nickname', 'Ləqəb'],
    userinfo_account: ['Account created', 'Hesab yaradılma'],
    userinfo_joined: ['Joined server', 'Serverə qoşulma'],
    userinfo_roles: ['Roles', 'Rollar'],
    userinfo_role_count: ['Role count', 'Rol sayı'],
    userinfo_nitro: ['Nitro booster', 'Nitro booster'],
    userinfo_warnings: ['Warnings', 'Xəbərdarlıqlar'],
    userinfo_timeout: ['Timeout', 'Timeout'],
    userinfo_no_timeout: ['No timeout', 'Timeout yoxdur'],
    userinfo_banned: ['Banned', 'Qadağan'],
    userinfo_failed: ['Could not get information about that user.', 'Bu istifadəçi haqqında məlumat əldə olunmadı.'],
    serverinfo_title: ['Server Info', 'Server Məlumatı'],
    serverinfo_name: ['Server name', 'Server adı'],
    serverinfo_id: ['Server ID', 'Server ID'],
    serverinfo_owner: ['Owner', 'Sahib'],
    serverinfo_created: ['Created', 'Yaradılma'],
    serverinfo_members: ['Members', 'Üzvlər'],
    serverinfo_channels: ['Channels', 'Kanallar'],
    serverinfo_roles: ['Roles', 'Rollar'],
    serverinfo_emojis: ['Emojis', 'Emojis'],
    serverinfo_boost: ['Boost level', 'Boost səviyyəsi'],
    serverinfo_failed: ['Could not get information about this server.', 'Bu server haqqında məlumat əldə olunmadı.'],

    // ----------------------------------------------------------------- AFK
    afk_set: ['You are now AFK: *{reason}*\nThis will be removed automatically when you send a message', 'İndi AFK oldunuz: *{reason}*\nMesaj göndərdiyinizdə bu avtomatik silinəcək'],
    afk_reason: ['Reason', 'Səbəb'],
    afk_notice: ['{user} is AFK ({minutes} minutes). {part}', '{user} AFK-dir ({minutes} dəqiqə). {part}'],
    afk_cleared: ['{user} is no longer AFK.', '{user} artıq AFK deyil.'],
    afk_reason_field: ['AFK reason', 'AFK səbəbi'],

    // ----------------------------------------------------------- giveaway
    giveaway_started: ['Giveaway started: **{prize}** ({duration})', 'Çəkiliş başladı: **{prize}** ({duration})'],
    giveaway_ended: ['Giveaway ended!', 'Çəkiliş bitdi!'],
    giveaway_winners: ['New winner: {winners}', 'Yeni qalib: {winners}'],
    giveaway_enter: ['You entered the giveaway! ({entrants} entrants)', 'Çəkilişə qoşuldunuz! ({entrants} iştirakçı)'],
    giveaway_already: ['You already entered this giveaway.', 'Siz artıq bu çəkilişə qoşulmusunuz.'],
    giveaway_ended_already: ['This giveaway has already ended.', 'Bu çəkiliş artıq bitib.'],
    giveaway_none_running: ['No giveaway is running right now.', 'Hazırda heç bir çəkiliş getmir.'],
    giveaway_disabled: ['The giveaway system is currently disabled.', 'Çəkiliş sistemi hazırda deaktivdir.'],
    giveaway_not_found: ['This giveaway was not found.', 'Bu çəkiliş tapılmadı.'],
    giveaway_in_progress: ['This giveaway is still running — a winner will be picked.', 'Bu çəkiliş hələ davam edir — qalib seçiləcək.'],
    giveaway_rerun: ['Starts a new giveaway or reruns the current one', 'Yeni çəkiliş başladır və ya cari çəkilişi təkrar başladır'],
    giveaway_no_participants: ['There are no participants left to pick a winner.', 'Qalib seçmək üçün iştirakçı yoxdur.'],
    giveaway_prize: ['Giveaway prize', 'Çəkilişin mükafatı'],
    giveaway_prize_opt: ['Prize', 'Mükafat'],
    giveaway_duration: ['Duration, e.g. 1h, 2d, 30m', 'Müddət, məs: 1h, 2d, 30m'],
    giveaway_winners_opt: ['Number of winners', 'Qalib sayı'],
    giveaway_message_id: ['Giveaway message id', 'Çəkiliş mesajının ID-si'],
    usage_giveaway: ['Usage: `!cekilis başlat <prize> <duration> [winners]`', 'İstifadə: `!cekilis başlat <mükafat> <müddət> [qalib sayı]`'],
    pick_winner: ['Pick a new winner for the giveaway', 'Çəkiliş üçün yeni qalib seç'],
    giveaway_hint: ['Pick a winner / start giveaway', 'Qalib seç / çəkiliş başlat'],

    // ------------------------------------------------------------ register
    register_panel_sent: ['Registration panel was sent to {channel}.', 'Qeydiyyat paneli {channel} kanalına göndərildi.'],
    register_done: ['Registration complete - your role has been granted.', 'Qeydiyyat tamamlandı - rolu verildi.'],
    register_failed: ['Registration failed. Please try again later.', 'Qeydiyyat uğursuz oldu. Bir az sonra yenidən cəhd edin.'],
    register_disabled: ['The registration system is currently disabled.', 'Qeydiyyat sistemi hazırda deaktivdir.'],
    register_no_role: ['The registration role is not set. Use `/register` to set a role.', 'Qeydiyyat rolu təyin edilməyib. Rol təyin etmək üçün `/register` istifadə edin.'],
    register_role_missing: ['The configured role was not found in the server.', 'Təyin edilmiş rol serverdə tapılmadı.'],
    register_already: ['You have already registered.', 'Siz artıq qeydiyyatdan keçmisiniz.'],
    register_set_panel: ['Sets up the registration panel (gives members a role)', 'Qeydiyyat panelini qurur (üzvə rol verir)'],
    register_set_role: ['Role given after registering', 'Qeydiyyatdan keçənə veriləcək rol'],
    usage_register: ['Usage: `!qeydiyyat #channel @role`', 'İstifadə: `!qeydiyyat #kanal @rol`'],
    opt_panel_channel: ['Channel the panel is sent to', 'Panelin göndəriləcəyi kanal'],
    opt_panel_role: ['Role', 'Rol'],

    // ------------------------------------------------------------- counting
    counting_enabled: ['Counting system enabled in channel: {channel}', 'Sayma sistemi aktivləşdirildi, kanal: {channel}'],
    counting_disabled: ['Counting system disabled.', 'Sayma sistemi söndürüldü.'],
    counting_set_channel: ['Sets the counting channel and enables the system', 'Sayma kanalını təyin edir və sistemi aktivləşdirir'],
    counting_toggle_off: ['Disables the counting system', 'Sayma sistemini söndürür'],
    opt_counting_channel: ['Counting channel', 'Sayma keçiriləcək kanal'],
    counting_wrong: ['The next number must be written correctly, and the same member cannot count twice in a row.', 'Növbəti rəqəm düzgün yazılmalıdır və eyni üzv ard-arda iki dəfə saya bilməz.'],
    counting_reset: ['Counting has been reset. The next number is 1.', 'Sayma sıfırlandı. Növbəti rəqəm 1-dir.'],

    // ------------------------------------------------------------- welcomer
    welcomer_enabled: ['Welcomer enabled (channel: {channel}{role})', 'Welcomer aktivləşdirildi (kanal: {channel}{role})'],
    welcomer_disabled: ['Welcomer disabled.', 'Welcomer söndürüldü.'],
    welcomer_no_channel: ['Please set a welcome channel first with `/welcomer channel`.', 'Əvvəlcə `/welcomer channel` ilə xoş gəldin kanalını təyin edin.'],
    welcomer_set: ['Set the welcomer channel, role and message', 'Welcomer kanalı, rolu və mesajını təyin et'],
    welcomer_toggle: ['Disables the welcomer system', 'Welcomer sistemini söndürür'],
    welcomer_set_welcome: ['Sets the welcome/leave message system', 'Xoş gəldin/çıxış mesajı sistemini qurur'],
    opt_welcome_channel: ['Welcome message channel', 'Xoş gəldin mesajı kanalı'],
    opt_leave_channel: ['Leave message channel', 'Çıxış mesajı kanalı'],
    opt_auto_role: ['Role given automatically', 'Avtomatik veriləcək rol'],
    opt_dm: ['Also send a direct message', 'Şəxsi mesaj da göndərilsin'],
    opt_welcome_text: ['Welcome message ({user} {username} {server} {membercount})', 'Xoş gəldin mesajı ({user} {username} {server} {membercount})'],
    usage_welcomer: ['Usage: `!welcomer qur #channel [role] [message]` or `!welcomer söndür`', 'İstifadə: `!welcomer qur #kanal [rol] [mesaj]` və ya `!welcomer söndür`'],

    // ------------------------------------------------------------- log system
    log_channel_set: ['Log channel set to {channel}.', 'Loq kanalı {channel} olaraq təyin edildi.'],
    log_enabled: ['Server log system enabled.', 'Server loq sistemi aktivləşdirildi.'],
    log_disabled: ['Server log system disabled.', 'Server loq sistemi söndürüldi.'],
    log_already: ['This channel is already the official AzeSpace / FoxCraft server log channel.', 'Bu kanal artıq AzeSpace / FoxCraft server loqları üçün rəsmi kanal olaraq təyin edilib.'],
    log_bad_channel: ['Please give a real text channel: `!setlog #channel`', 'Zəhmət olmasa düzgün bir mətn kanalı qeyd edin: `!setlog #kanal`'],
    log_missing_perms: ['The bot is missing these permissions in {channel}:', 'Botun {channel} kanalında aşağıdakı icazələri yoxdur:'],
    log_set_channel: ['Sets the channel that server logs are sent to', 'Server loqlarının göndəriləcəyi kanalı təyin edir'],
    opt_log_channel: ['Text channel to send logs to', 'Loqların göndəriləcəyi mətn kanalı'],
    logstatus_off: ['Disabled (no channel assigned)', 'Deaktiv (Kanal təyin edilməyib)'],
    logstatus_unassigned: ['*Not assigned*', '*Təyin edilməyib*'],
    logstatus_none: ['*None*', '*Yoxdur*'],
    logstatus_assign_help: ['Use `{cmd} #channel` to assign a channel so the log system can work.', 'Loqların işləməsi üçün `{cmd} #kanal` əmri ilə kanal təyin edin.'],
    logstatus_error_missing: ['Error (assigned channel not found or deleted)', 'Xəta (Təyin olunmuş kanal tapılmadı və ya silinib)'],
    logstatus_not_found: ['Not found', 'Tapılmadı'],
    logstatus_channel_gone: ['The assigned channel no longer exists on the server. Use `{cmd} #channel` to pick a new one.', 'Təyin olunmuş kanal serverdə mövcud deyil. `{cmd} #kanal` ilə yeni kanal seçin.'],
    logstatus_warn_perms: ['Warning (missing permissions)', 'Diqqət (İcazə çatışmazlığı)'],
    logstatus_missing_perms: ['The bot is missing some permissions in this channel:\n{list}', 'Botun bu kanalda bəzi icazələri yoxdur:\n{list}'],
    logstatus_ok_ready: ['Active and ready', 'Aktiv və Hazır'],
    logstatus_health_ok: ['The bot has every required permission (`ViewChannel`, `SendMessages`, `EmbedLinks`). All server events are being logged.', 'Bot tələb olunan bütün icazələrə malikdir (`ViewChannel`, `SendMessages`, `EmbedLinks`). Bütün server hadisələri qeyd olunur.'],
    logstatus_ok: ['Active', 'Aktiv'],
    logstatus_assigned: ['A channel has been assigned.', 'Kanal təyin edilib.'],
    logstatus_health_field: ['Health and permissions', 'Sağlamlıq və İcazələr'],
    logstatus_change_field: ['Change the channel', 'Kanalı dəyişmək'],
    logstatus_change_help: ['Use `{cmd} #channel` to assign or change the log channel.', 'Loq kanalını dəyişmək və ya təyin etmək üçün `{cmd} #kanal` əmrindən istifadə edin.'],
    logstatus_footer: ['FoxCraft Server Log System', 'FoxCraft Server Loq Sistemi'],
    perm_view_channel: ['View Channel', 'Kanala Baxmaq'],
    perm_send_messages: ['Send Messages', 'Mesaj Göndərmək'],
    perm_embed_links: ['Embed Links', 'Embed Linklər'],
    logstatus_title: ['Server Log Status', 'Server Loq Sistemi Statusu'],
    logstatus_text: ['Log settings for **{server}**:', '**{server}** serveri üçün loq parametrləri:'],
    logstatus_channel: ['Channel', 'Kanal'],
    logstatus_channel_id: ['Channel ID', 'Kanal ID'],
    logstatus_change_channel: ['Change channel', 'Kanalı dəyişmək'],
    logstatus_status: ['Status', 'Status'],
    logstatus_status_field: ['Log System Status', 'Loq Sistemi Statusu'],
    opt_log_show: ['Show the current log system status', 'Server loq sisteminin hazırkı vəziyyətini göstərir'],
    setlog_activated: ['Server log system enabled', 'Server Loq Sistemi Aktivləşdirildi'],
    setlog_success: ['Log channel set successfully', 'Loq Kanalı Uğurla Təyin Edildi'],
    setlog_perm_advice: ['Please give the bot these permissions in that channel and try again.', 'Zəhmət olmasa həmin kanalın parametrlərindən bota bu icazələri verin və yenidən cəhd edin.'],
    setlog_bad_channel_prefix: ['Please pick a valid text channel: `{cmd} #kanal`', 'Zəhmət olmasa düzgün bir mətn kanalı qeyd edin: `{cmd} #kanal`'],
    setlog_test_footer: ['FoxCraft Log System', 'FoxCraft Loq Sistemi'],
    setlog_change_footer: ['Run `{cmd}` again if you want to change it.', 'Dəyişmək üçün yenidən `{cmd}` əmrini istifadə edə bilərsiniz.'],
    setlog_title: ['Log System', 'Loq Sistemi'],
    setlog_set_channel: ['Assigned channel', 'Təyin Edilmiş Kanal'],
    setlog_date: ['Date', 'Tarix'],
    setlog_assigned_by: ['Assigned by', 'Təyin Edən'],

    // --------------------------------------------------------------- automod
    automod_title: ['Automod', 'Automod'],
    automod_filter_links: ['Links', 'Keçidlər'],
    automod_filter_invites: ['Invites', 'Dəvət linkləri'],
    automod_filter_caps: ['Caps', 'Böyük hərflər'],
    automod_filter_spam: ['Spam/Flood', 'Spam/Flood'],
    automod_action_delete: ['Delete message', 'Mesajı sil'],
    automod_action_warn: ['Warn', 'Xəbərdarlıq'],
    automod_action_timeout: ['Timeout (10 min)', 'Zaman aşımı (10 dəq)'],
    automod_status_line: ['Status: **{status}**', 'Status: **{status}**'],
    automod_enabled: ['Enabled', 'Aktiv'],
    automod_disabled: ['Disabled', 'Deaktiv'],
    automod_action_line: ['Action: {action}', 'Hərəkət: {action}'],
    automod_none: ['None', 'Yoxdur'],
    automod_select_filters: ['Select filters', 'Süzgəcləri seç'],
    automod_desc_on: ['Enabled - deselect to turn off', 'Aktiv - söndürmək üçün seçimi qaldır'],
    automod_desc_off: ['Disabled - select to turn on', 'Deaktiv - aktivləşdirmək üçün seç'],
    automod_select_action: ['Select action', 'Hərəkəti seç'],
    automod_disable: ['Disable', 'Deaktiv et'],
    automod_enable: ['Enable', 'Aktiv et'],
    automod_perm: ['Manage Guild permission is required for this action.', 'Bu əməliyyat üçün Manage Guild icazəsi lazımdır.'],
    automod_manage: ['Manages the automod filters', 'Avtomatik veriləcək rol filterlərini idarə edir'],
    automod_banned_words: ['Banned words', 'Qadağan sözlər'],
    automod_exempt_channels: ['Exempt channels', 'İstisna kanallar'],
    automod_exempt_roles: ['Exempt roles', 'İstisna rollar'],
    automod_triggers: ['A message was blocked by automod', 'Avtomatik filtr mesajı blokladı'],

    // ---------------------------------------------------------------- panel
    panel_mod_automod: ['Automod', 'Automod'],
    panel_mod_welcomer: ['Welcomer', 'Welcomer'],
    panel_mod_sayma: ['Counting', 'Sayma'],
    panel_mod_cekilis: ['Giveaway', 'Çəkiliş'],
    panel_mod_ticket: ['Ticket', 'Ticket'],
    panel_mod_qeydiyyat: ['Register', 'Qeydiyyat'],
    panel_mod_afk: ['AFK', 'AFK'],
    panel_mod_modlog: ['Mod log', 'Mod-loq'],
    panel_embed_title: ['Bot Control Panel', 'Bot İdarəetmə Paneli'],
    panel_usage_field: ['Usage', 'İstifadə'],
    panel_usage_value: ['Pick a module, then enable/disable it or open its settings.', 'Modulu seç, sonra Aktiv/Deaktiv və ya Ayarlar.'],
    panel_select_module: ['Select a module', 'Modulu seç'],
    panel_disable: ['Disable', 'Deaktiv et'],
    panel_enable: ['Enable', 'Aktiv et'],
    panel_settings: ['Settings', 'Ayarlar'],
    panel_refresh: ['Refresh', 'Yenilə'],
    panel_restart_btn: ['Restart bot', 'Botu yenidən başlat'],
    panel_toggle_on_msg: ['**{label}** enabled.', '**{label}** aktivləşdirildi.'],
    panel_toggle_off_msg: ['**{label}** disabled.', '**{label}** söndürüldü.'],
    panel_saved: ['Setting changed and saved.', 'Ayar dəyişildi və saxlandı.'],
    panel_no: ['No', 'Xeyr'],
    panel_welcomer_title: ['Welcomer Settings', 'Welcomer Ayarlar'],
    panel_welcomer_channel: ['Welcome channel ID', 'Xoş gəldin kanal ID'],
    panel_welcomer_leave: ['Leave channel ID', 'Çıxış kanal ID'],
    panel_welcomer_autorole: ['Auto-role ID', 'Avto-rol ID'],
    panel_welcomer_message: ['Welcome message', 'Xoş gəldin mesajı'],
    panel_welcomer_dm: ['Send DM (0/1)', 'DM göndərilsin (0/1)'],
    ph_channel_id: ['Channel ID', 'Kanal ID'],
    ph_channel_id_opt: ['Channel ID (can be empty)', 'Kanal ID (boş ola bilər)'],
    ph_role_id: ['Role ID', 'Rol ID'],
    ph_role_id_opt: ['Role ID (can be empty)', 'Rol ID (boş ola bilər)'],
    ph_channel_ids: ['Channel IDs', 'Kanal ID-ləri'],
    ph_role_ids: ['Role IDs', 'Rol ID-ləri'],
    ph_message_vars: ['Text: {user} {username} {server} {membercount}', 'Mətn: {user} {username} {server} {membercount}'],
    ph_0_or_1: ['1 or 0', '1 və ya 0'],
    ph_words: ['word1, word2, ...', 'söz1, söz2, ...'],
    panel_sayma_title: ['Counting Settings', 'Sayma Ayarlar'],
    panel_sayma_channel: ['Counting channel ID', 'Sayma kanal ID'],
    panel_ticket_title: ['Ticket Settings', 'Ticket Ayarlar'],
    panel_ticket_category: ['Category ID', 'Kateqoriya ID'],
    ph_ticket_category: ['Ticket category ID (empty = automatic)', 'Ticket kateqoriyasının ID-si (boş = avtomatik)'],
    panel_qeydiyyat_title: ['Register Settings', 'Qeydiyyat Ayarlar'],
    panel_qeydiyyat_channel: ['Panel channel ID', 'Panel kanal ID'],
    panel_qeydiyyat_role: ['Role ID to give', 'Veriləcək rol ID'],
    panel_qeydiyyat_message: ['Panel message (text)', 'Panel mesajı (mətn)'],
    ph_panel_title: ['Panel title', 'Panel başlığı'],
    panel_modlog_title: ['Mod Log Settings', 'Mod-loq Ayarlar'],
    panel_modlog_channel: ['Mod log channel ID', 'Mod-loq kanal ID'],
    panel_automod_filters_title: ['Automod - Filters', 'Automod - Süzgəclər'],
    panel_automod_words_title: ['Automod - Words', 'Automod - Sözlər'],
    panel_automod_exceptions_title: ['Automod - Exceptions', 'Automod - İstisnalar'],
    panel_auto_links: ['Links (1/0)', 'Keçidlər (1/0)'],
    panel_auto_invites: ['Invites (1/0)', 'Dəvət linkləri (1/0)'],
    panel_auto_caps: ['Caps (1/0)', 'Böyük hərflər (1/0)'],
    panel_auto_spam: ['Spam/Flood (1/0)', 'Spam/Flood (1/0)'],
    panel_auto_action: ['Action (delete/warn/timeout)', 'Hərəkət (delete/warn/timeout)'],
    panel_auto_words: ['Banned words (comma separated)', 'Qadağan sözlər (vergüllə)'],
    panel_auto_exc_roles: ['Exempt roles (IDs, comma separated)', 'İstisna rollar (ID-lər vergüllə)'],
    panel_auto_exc_channels: ['Exempt channels (IDs, comma separated)', 'İstisna kanallar (ID-lər vergüllə)'],
    panel_automod_settings_title: ['Automod - Settings', 'Automod - Ayarlar'],
    panel_automod_pick: ['Which settings do you want to change?', 'Hansı parametrləri dəyişmək istəyirsən?'],
    panel_auto_param: ['Select a setting', 'Parametr seç'],
    panel_auto_filters_label: ['Filters', 'Süzgəclər'],
    panel_auto_exceptions_label: ['Exceptions (roles/channels)', 'İstisnalar (rollar/kanallar)'],
    panel_title: ['Bot Control Panel', 'Bot İdarəetmə Paneli'],
    panel_usage: ['Usage', 'İstifadə'],
    panel_restart: ['Restart bot', 'Botu yenidən başlat'],
    panel_restart_confirm: ['Restart the bot? This will take a few seconds.', 'Bot yenidən başladılsın? Bu bir neçə saniyə davam edəcək.'],
    panel_restarting: ['Restarting the bot...', 'Bot yenidən başladılır...'],
    panel_restart_cancelled: ['Restart cancelled.', 'Yenidən başlatma ləğv edildi.'],
    panel_no_modal: ['This module has no settings panel — just use Enable/Disable.', 'Bu modul üçün ayar modalı yoxdur — sadəcə Aktiv/Deaktiv istifadə olunur.'],
    panel_unknown: ['Unknown setting.', 'Naməlum ayar.'],
    panel_admin_only: ['Only administrators can use this panel.', 'Bu paneldən yalnız Administratorlar istifadə edə bilər.'],

    // ----------------------------------------------------------------- help
    help_title: ['FoxCraft Commands', 'FoxCraft Əmrləri'],
    help_category: ['Category', 'Kateqoriya'],
    help_command: ['Command', 'Əmr'],
    help_description: ['Description', 'Təsvir'],
    help_prefix_hint: ['Category name or command name', 'Kateqoriya və ya əmr adı'],
    help_usage: ['Usage', 'İstifadə'],
    help_prefix: ['Prefix', 'Prefiks'],
    help_category_core: ['Core', 'Əsas'],
    help_category_mod: ['Moderation', 'Moderasiya'],
    help_category_music: ['Music', 'Musiqi'],
    help_category_fun: ['Fun', 'Əyləncə'],
    help_category_bot: ['Bot', 'Bot'],
    help_category_setup: ['Setup', 'Qurulum'],
    help_category_menus: ['Menus', 'Menyu'],
    help_category_user: ['User', 'İstifadəçi'],

    // ---------------------------------------------------------------- misc
    avatar_failed: ['Could not get that user avatar.', 'İstifadəçinin avatarları əldə olunmadı.'],
    ip_intro: ['FoxCraft server IP:', 'FoxCraft server IP:'],
    link_usage: ['Usage: `!link <minecraft_username>`', 'İstifadə: `!link <minecraft_istifadəçi_adı>`'],
    link_success: ['Your Discord account is now linked to **{username}**.', 'Discord hesabınız **{username}** ilə bağlandı.'],
    link_failed: ['Could not link your account. Check the username and try again.', 'Hesabınız bağlanmadı. İstifadəçi adını yoxlayın və yenidən cəhd edin.'],
    opt_minecraft_username: ['Minecraft username', 'Minecraft istifadəçi adı'],
    qrkod_usage: ['Usage: `!qrkod <text>`', 'İstifadə: `!qrkod <mətn>`'],
    opt_qr_text: ['Text to turn into a QR code', 'QR koda çevriləcək mətn'],
    rules_intro: ['FoxCraft rules', 'FoxCraft qaydaları'],
    server_status: ['Shows the FoxCraft Minecraft server status', 'FoxCraft Minecraft server statusunu göstərir'],
    status_intro: ['Shows the live status of the FoxCraft Minecraft server', 'FoxCraft Minecraft serverinin canlı statusunu göstərir'],
    status_online: ['Online', 'Onlayn'],
    status_offline: ['Offline', 'Offlayn'],
    status_players: ['Players', 'Oyunçular'],
    ping_desc: ['Shows the bot and Discord latency', 'Bot və Discord gecikməsini göstərir'],
    whoami_desc: ['Shows your linked Minecraft username', 'Əlaqələndirilmiş Minecraft istifadəçi adını göstərir'],
    whoami_none: ['Your account is not linked to a Minecraft username yet.', 'Hesabınız hələ Minecraft istifadəçi adı ilə əlaqələndirilməyib.'],
    foxcraft_desc: ['Shows FoxCraft server information', 'FoxCraft server məlumatlarını göstərir'],
    foxcraft_server_ip: ['Server IP', 'Server IP'],
    foxcraft_version: ['Version', 'Versiya'],
    foxcraft_members: ['Members', 'Üzvlər'],
    restart_desc: ['Restarts the bot (owner only)', 'Botu yenidən başladır (yalnız sahib)'],
    restart_confirm: ['Restart the bot?', 'Bot yenidən başladılsın?'],
    servericon_usage: ['Usage: `!servericon` (attach the image to the slash command instead)', 'İstifadə: `!servericon` (şəkli slash əmrinə əlavə edin)'],
    servericon_no_logo: ['No logo source is configured (FOXCRAFT_LOGO_URL or FOXCRAFT_LOGO_FILE).', 'Logo mənbəyi yoxdur (FOXCRAFT_LOGO_URL və ya FOXCRAFT_LOGO_FILE).'],
    servericon_bad_type: ['The image must be a PNG, JPEG or GIF file.', 'Şəkil PNG, JPEG və ya GIF olmalıdır.'],
    servericon_too_big: ['The image must be smaller than 256 KB.', 'Şəkil 256 KB-dan kiçik olmalıdır.'],
    servericon_download: ['The configured image could not be downloaded.', 'Təyin edilmiş şəkil yüklənmədi.'],
    servericon_done: ['The server icon was updated.', 'Server ikonu yeniləndi.'],
    servericon_opt: ['PNG, JPEG or GIF under 256 KB. Leave empty to use the configured logo.', '256 KB-dan kiçik PNG, JPEG və ya GIF. Boş buraxsanız təyin edilmiş logo istifadə olunur.'],
    foxcraft_manage: ['Sets up the FoxCraft channels, roles and panels', 'FoxCraft kanallarını, rollarını və panellərini qurur'],
    foxcraft_rebrand: ['Rebrands this server as FoxCraft', 'Bu serveri FoxCraft olaraq rebrend edir'],
    sunucukur_manage: ['Sets up the whole server with one button (channels, roles, panels)', 'Serveri bir düymə ilə tam qurur (kanallar, rollar, panellər)'],

    ticket_setup_desc: ['Sets up the ticket system panel', 'Dəstək sisteminin panelini qurur'],
    counting_enabled_hint: ['Set the counting channel and enable the system', 'Sayma kanalını təyin et və sistemi aktivləşdir'],
    mod_no_reason: ['No reason given.', 'Səbəb göstərilməyib.'],
    mod_action_desc: ['Manages a member with the {name} action', '{name} əməliyyatı ilə üzvü idarə edir'],
    logstatus_permissions: ['Health and permissions', 'Sağlamlıq və İcazələr'],
    givepick_hint: ['Pick a winner / start giveaway', 'Qalib seç / çəkiliş başlat'],


    // ------------------------------------------- strings not yet extracted
    role_already_has: ['{user} already has the {role} role.', '{user} artıq {role} roluna malikdir.'],
    role_not_has: ['{user} does not have the {role} role.', '{user} {role} roluna malik deyil.'],
    giveaway_disabled_panel: ['The giveaway system is disabled. Enable it from the panel.', 'Çəkiliş sistemi deaktivdir. Paneldən aktivləşdirmək lazımdır.'],
    giveaway_need_prize: ['Please enter a prize for the giveaway.', 'Çəkiliş mükafatını yaz.'],
    giveaway_bad_duration: ['Enter a valid duration: `1h`, `30m`, `2d`.', 'Düzgün müddət yaz: `1h`, `30m`, `2d`.'],
    giveaway_no_channel: ['No suitable channel was found.', 'Uyğun kanal tapılmadı.'],
    giveaway_started_with_channel: ['Giveaway started: **{prize}** ({duration})\nPrize: <#{channel}>', 'Çəkiliş başladı: **{prize}** ({duration})\nMükafat: <#{channel}>'],
    giveaway_winners_line: ['New winner: {winners}', 'Yeni qalib: {winners}'],
    giveaway_start_failed: ['The giveaway could not be started.', 'Çəkiliş başladılmadı.'],
    foxcraft_server_only: ['FoxCraft can only be used on a server.', 'FoxCraft yalnız serverdə istifadə oluna bilər.'],
    foxcraft_not_checked: ['FoxCraft server information was not checked. Check the bot access and permissions.', 'FoxCraft server məlumatları yoxlanılmadı. Botun serverə girişini və icazələrini yoxla.'],
    mc_username_invalid: ['The Minecraft username must be 3-16 characters and may only contain letters, numbers and underscores.', 'Minecraft istifadəçi adı 3-16 simvol olmalıdır və yalnız hərf, rəqəm və alt xətt ola bilər.'],
    lock_already: ['The channel is already locked.', 'Bu kanal artıq kilidlidir.'],
    unlock_already: ['The channel is already unlocked.', 'Bu kanal artıq açıqdır.'],
    logstatus_server_only: ['This command can only be used on a Discord server.', 'Bu əmr yalnız Discord serverində istifadə edilə bilər.'],
    logstatus_no_guild: ['Server information could not be loaded.', 'Server məlumatları əldə edilmədi.'],
    mute_bad_duration: ['Enter a valid duration: `1s`, `1m`, `1h`, `1d`, `1w` or a combination (`1h30m`). Maximum 28 days.', 'Düzgün müddət yaz: `1s`, `1m`, `1h`, `1d`, `1w` və ya birləşmə (`1h30m`). Maximum 28 gün.'],
    timeout_bad_duration: ['Enter a valid duration up to 28 days: `10m`, `2h`, `7d` or a combination (`1h30m`).', '28 günə qədər düzgün müddət yaz: `10m`, `2h`, `7d` və ya birləşmə (`1h30m`).'],
    nickname_not_empty: ['The nickname cannot be empty. Send the command without a nickname to reset it.', 'Ləqəb boş ola bilməz. Sıfırlamaq üçün əmri ləqəbsiz göndərin.'],
    register_no_channel_role: ['Please select a channel and a role.', 'Kanal və rol seçilmədi.'],
    register_bad_channel: ['The selected channel is not suitable.', 'Seçilən kanal uyğun deyil.'],
    register_panel_failed: ['The panel could not be sent.', 'Panel göndərilmədi.'],
    qr_no_text: ['Please enter the text for the QR code.', 'QR kod üçün mətn daxil etməlisən.'],
    usage_counting: ['Usage: `!sayma qur #channel` or `!sayma söndür`', 'İstifadə: `!sayma qur #kanal` və ya `!sayma söndür`'],
    counting_no_channel: ['Please select a channel.', 'Kanal seçilmədi.'],
    counting_announce: ['Counting system enabled in channel: {channel}\nCount up in order starting from 1; a wrong message is deleted.', 'Sayma sistemi aktivləşdirildi, kanal: {channel}\n1-dən başlayaraq ardıcıl sayın; səhv yazan mesaj silinər.'],
    welcomer_autorole: [', auto role: {role}', ', avto-rol: {role}'],
    servericon_no_image: ['No image was attached and no logo source is configured (FOXCRAFT_LOGO_URL or FOXCRAFT_LOGO_FILE).', 'Şəkil əlavə edilməyib və logo mənbəyi təyin edilməyib (FOXCRAFT_LOGO_URL və ya FOXCRAFT_LOGO_FILE).'],
    servericon_failed: ['The server icon could not be updated.', 'Server ikonu yenilənmədi.'],
    setlog_server_only: ['This command can only be used on a Discord server.', 'Bu əmr yalnız Discord serverində istifadə edilə bilər.'],
    setlog_no_channel: ['Please select a channel.', 'Kanal seçilmədi.'],
    setlog_no_guild: ['Server information could not be loaded.', 'Server məlumatları əldə edilmədi.'],
    setlog_bad_channel: ['That channel was not found or it is not a text channel.', 'Seçilən kanal tapılmadı və ya uyğun mətn kanalı deyil.'],
    skip_failed: ['The track could not be skipped.', 'Trek keçilə bilmədi.'],
    slowmode_bad_number: ['Enter a valid number of seconds.', 'Düzgün saniyə sayı yaz.'],
    softban_done: ['{user} was softbanned and has been unbanned.', '{user} softban edildi və qadağanı ləğv edildi.'],
    softban_done_kept: ['{user} was softbanned and remains banned.', '{user} softban edildi və qadağan davam edir.'],
    ticket_create_button: ['Ticket Yarat', 'Ticket Yarat'],
    welcomer_no_channel_select: ['Please select a channel.', 'Kanal seçilmədi.'],
    help_slash_hint: ['/`{name}`', '/`{name}`'],
    log_field_messages_deleted: ['Messages deleted', 'Silinen mesajlar'],
    log_field_remaining: ['Remaining members', 'Qalan üzvlər'],


    // ------------------------------------------------ logger leftovers
    log_unknown_author: ['Unknown author', 'Naməlum müəllif'],
    log_unknown_staff: ['Unknown moderator', 'Naməlum moderator'],
    log_no_reason: ['No reason given', 'Səbəb göstərilməyib'],
    log_not_determined: ['Not determined', 'Müəyyən edilmədi'],
    log_unknown: ['Unknown', 'Naməlum'],
    log_not_in_cache: ['*[Not in cache / Empty]*', '*[Keşdə yoxdur / Boş]*'],
    log_was_not_in_cache: ['*[Was not in cache]*', '*[Keşdə deyildi]*'],
    log_content_empty: ['*[Content is empty]*', '*[Məzmun boşdur]*'],
    log_yes: ['Yes', 'Bəli'],
    log_no: ['No', 'Xeyr'],
    log_none: ['*None*', '*Yoxdur*'],
    log_none_plain: ['None', 'Yoxdur'],
    log_channel_id_footer: ['Channel ID: {id}', 'Kanal ID: {id}'],
    log_role_id_footer: ['Role ID: {id}', 'Rol ID: {id}'],
    log_server_id_footer: ['Server ID: {id}', 'Server ID: {id}'],
    log_change_permissions: ['Role permissions were changed.', 'Rol icazələri dəyişdirildi.'],
    log_change_server_icon: ['Server icon changed.', 'Server ikonu dəyişdirildi.'],
    log_change_server_name: ['Server name: `{old}` -> `{new}`', 'Server adı: `{old}` -> `{new}`'],
    log_change_boost_tier: ['Boost level (tier): `{old}` -> `{new}`', 'Boost səviyyəsi (tier): `{old}` -> `{new}`'],
    log_change_boost_count: ['Boost count: `{old}` -> `{new}`', 'Boost sayı: `{old}` -> `{new}`'],
    log_change_color: ['Color: `{old}` -> `{new}`', 'Rəng: `{old}` -> `{new}`'],
    log_change_topic: ['Topic: `{old}` -> `{new}`', 'Mövzu: `{old}` -> `{new}`'],
    log_change_slowmode: ['Slowmode: `{old}` -> `{new}`', 'Slowmode: `{old}` -> `{new}`'],
    log_change_category: ['Category: `{old}` -> `{new}`', 'Kateqoriya: `{old}` -> `{new}`'],
    log_field_permissions: ['Permissions', 'İcazələr'],
    log_field_server_icon: ['Server icon', 'Server ikonu'],
    log_field_name: ['Name', 'Ad'],
    log_field_mention: ['Mention', 'Qeyd etmə'],
    log_change_name: ['Name: `{old}` -> `{new}`', 'Ad: `{old}` -> `{new}`'],
    log_change_hoist: ['Displayed separately: `{old}` -> `{new}`', 'Ayrıca göstərilir: `{old}` -> `{new}`'],
    log_change_mention: ['Mention: `{old}` -> `{new}`', 'Qeyd etmə: `{old}` -> `{new}`'],
    log_msg_id_footer: ['Message ID: {msg} | Author ID: {author}', 'Mesaj ID: {msg} | Müəllif ID: {author}'],
    log_user_id_footer: ['User ID: {id}', 'İstifadəçi ID: {id}'],
    log_type_category: ['Category', 'Kateqoriya'],
    log_type_voice: ['Voice', 'Səs'],
    log_type_announcement: ['Announcement', 'Elan'],
    log_type_stage: ['Stage', 'Səhnə'],
    log_type_forum: ['Forum', 'Forum'],
    log_type_other: ['Other', 'Digər'],


    // ------------------------------------------------------------- help menu
    help_cat_user: ['User', 'İstifadəçi'],
    help_cat_moderation: ['Moderation', 'Moderasiya'],
    help_cat_bot: ['Bot', 'Bot'],
    help_cat_systems: ['Systems', 'Sistemlər'],
    help_hint_user: ['Profile, server and personal commands', 'Profil, server və şəxsi əmrlər'],
    help_hint_moderation: ['Punishments, management and automatic rules', 'Cəzalar, idarəetmə və avtomatik qaydalar'],
    help_hint_bot: ['Help, panel and bot commands', 'Kömək, panel və bot əmrləri'],
    help_hint_systems: ['Counting, giveaway, welcomer and ticket', 'Sayma, çəkiliş, welcomer və ticket'],
    help_no_commands: ['_There are no commands you can use in this category._', '_Bu kateqoriyada istifadə edə biləcəyiniz əmr yoxdur._'],
    help_hidden_count: ['> {count} commands are hidden because you lack permission.', '> {count} əmr icazəniz olmadığı üçün gizlədilib.'],
    help_shown_count: ['**{shown}/{total}** commands shown - about a command: `{prefix}help <command>`', '**{shown}/{total}** əmr göstərilir - əmr haqqında: `{prefix}help <command>`'],
    help_embed_title: ['Help - {title}', 'Kömək - {title}'],
    help_badge_enabled: [' [enabled]', ' [aktiv]'],
    help_badge_disabled: [' [disabled]', ' [deaktiv]'],
    help_field_status_name: ['Enabled / Disabled', 'Aktiv / Deaktiv'],
    help_field_status_value: ['For system commands, shows whether the module is currently on or off.', 'Sistem əmrləri üçün modulun hazırda aktiv və ya deaktiv olduğunu göstərir.'],
    help_field_menus_name: ['Menus', 'Menyular'],
    help_field_menus_value: ['Use the menu below to switch category, and use `/panel` to manage modules.', 'Kateqoriyanı dəyişmək üçün aşağıdakı menyudan istifadə edin, modulları idarə etmək üçün `/panel`.'],
    help_select_placeholder: ['Select a category', 'Kateqoriya seçin'],
    help_param_line: ['- `<{name}>` {desc}{required}', '- `<{name}>` {desc}{required}'],
    help_no_description: ['No description', 'Təsvir yoxdur'],
    help_required: [' *(required)*', ' *(məcburi)*'],
    help_sub_line: ['- `{name} {sub}` {desc}', '- `{name} {sub}` {desc}'],
    help_module_line: ['**Module:** {status}', '**Modul:** {status}'],
    help_parameters: ['Parameters', 'Parametrlər'],
    help_subcommands: ['Subcommands', 'Alt əmrlər'],
    help_status_enabled: ['Enabled', 'Aktiv'],
    help_status_disabled: ['Disabled', 'Deaktiv'],
    help_category_other: ['Other', 'Digər'],
    foxcraft_players: ['Players', 'Oyunçular'],
    giveaway_ends: ['Ends', 'Son'],
    giveaway_winners: ['Winners', 'Qaliblər'],
    giveaway_entrants: ['Entrants', 'İştirakçılar'],
    giveaway_host: ['Host', 'Həstad'],
    queue_title: ['Queue', 'Növbə'],
    queue_footer: ['{count} tracks queued | Volume: {volume}% | Loop: {loop}', '{count} trek növbədə | Səs: {volume}% | Təkrarlama: {loop}'],
    np_duration: ['Duration', 'Müddət'],
    np_volume: ['Volume', 'Səs'],
    np_loop: ['Loop', 'Təkrarlama'],
    np_queue: ['Queue', 'Növbə'],
    warnings_more: ['...and {count} more warnings', '...və {count} xəbərdarlıq daha çoxdur'],
    warnings_footer: ['{count} warnings - use !removewarn @member #id', '{count} xəbərdarlıq - !removewarn @üzv #id'],
    common_none: ['None', 'Yoxdur'],
    giveaway_ended_title: ['This giveaway has ended.', 'Bu çəkiliş sona çatdı.'],
    giveaway_join: ['Join', 'Qatıl'],
    ip_title: ['FoxCraft server information', 'FoxCraft server məlumatları'],
    nowplaying_title: ['Now playing', 'İndi oynadılır'],
    nowplaying_requested: ['Requested by', 'Səsləndirən'],
    play_searching: ['Searching...', 'Axtarılır...'],
    qeydiyyat_title: ['Register', 'Qeydiyyat'],
    qeydiyyat_intro: ['Press the button below to register and get your role.', 'Aşağıdakı düyməyə basaraq qeydiyyatdan keç və rolunu al.'],
    qeydiyyat_button: ['Register', 'Qeydiyyatdan keç'],
    owner_only_panel: ['Only the bot owner can use this panel.', 'Bu paneldən yalnız bot sahibi istifadə edə bilər.'],
    restart_yes: ['Yes, restart', 'Bəli, yenidən başlat'],
    rules_title: ['FoxCraft Rules', 'FoxCraft Qaydaları'],
    server_status_title: ['FoxCraft server status', 'FoxCraft server statusu'],
    warnings_title_line: ['Warnings for', 'Xəbərdarlıqlar'],
    foxcraft_dry_run: ['Dry run is active: nothing was changed.', 'Dry run aktivdir: heç bir dəyişiklik edilmədi.'],
    foxcraft_perms_unchecked: ['Bot permissions: not checked (the fresh member fetch failed)', 'Bot icazələri: yoxlanılmadı (fresh member fetch uğursuz oldu)'],
    foxcraft_server_name: ['Server name', 'Server adı'],
    foxcraft_bot_nick: ['Bot nickname', 'Bot ləqəbi'],
    foxcraft_bot_avatar: ['Bot avatar', 'Bot avatarı'],
    foxcraft_no_logo: ['No logo source', 'Logo mənbəyi yoxdur'],
    giveaway_ended_desc: ['The giveaway has ended! **Winners:** {winners}\nCongratulations!', 'Çəkiliş bitdi! **Qaliblər:** {winners}\nTəbriklər!'],
    giveaway_cancelled: ['Nobody entered, so the giveaway was cancelled.', 'Heç kim qoşulmadı, çəkiliş ləğv edildi.'],
    giveaway_footer: ['Giveaway ended - {count} entrants', 'Çəkiliş bitdi - {count} iştirakçı'],
    giveaway_no_winners: ['No winners', 'Qalib yoxdur'],

    // -------------------------------------------------- FUNCTIONAL NAMES
    // These are identifiers, not text. Both languages are identical on purpose so
    // setup keeps creating exactly the same channel/panel names.
    fn_support: ['Dəstək', 'Dəstək'],
    fn_support_rule: ['Dəstək qaydası', 'Dəstək qaydası'],
    fn_chat: ['Söhbət', 'Söhbət'],
    fn_rules: ['Qayda', 'Qayda'],
    fn_privacy: ['Məxfilik', 'Məxfilik'],
    fn_how_to_send: ['Necə göndərim?', 'Necə göndərim?'],
    fn_what_to_do: ['Nə etməlisən?', 'Nə etməlisən?'],
    fn_reply_time: ['Cavab müddəti', 'Cavab müddəti'],
    fn_voice_channels: ['Səs kanalları', 'Səs kanalları'],
    fn_checkmark: ['foxcraft_check', 'foxcraft_check'],
};
